version: '3.3'
services:
  app:
    build: .
    command: bin/rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
      - bundle-data:/usr/local/bundle
      - node-data:/app/node_modules
      - sprockets-data:/sprockets_cache
    ports:
      - 3000:3000
    environment:
      TZ: Asia/Tokyo
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      SPROCKETS_CACHE: /sprockets_cache
    depends_on:
      - db
  db:
    image: mysql:5.7.31
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  bundle-data:
  sprockets-data:
  node-data:
  db-data:
